# Generated by Django 3.2.12 on 2022-03-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='inviter',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.TextField(default=None, unique=True),
        ),
    ]
