# Generated by Django 3.2.12 on 2022-03-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220313_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.TextField(blank=True, default=None, unique=True),
        ),
    ]
