# Generated by Django 3.2.12 on 2022-03-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220313_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='inviter',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.TextField(null=True, unique=True),
        ),
    ]
