# Generated by Django 3.2.12 on 2022-03-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='verify_code',
            field=models.IntegerField(default=123, max_length=3),
        ),
    ]
