# Generated by Django 3.2.12 on 2022-03-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_settings_verify_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='settings',
            name='verify_code',
            field=models.IntegerField(default=123),
        ),
    ]
