# Generated by Django 3.2.12 on 2022-03-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20220317_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramusers',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
